"use client";

import { useState } from "react";
import Link from "next/link";
import FadeIn from "@/components/FadeIn";

interface BlogPost {
  id: number;
  title: string;
  date: string;
  excerpt: string;
  category: string;
  readTime: string;
  type: "AI+HI" | "HI";
}

const posts: BlogPost[] = [
  {
    id: 9,
    title: "Cape Town: Twenty Essential Encounters in the Mother City",
    date: "2026-06-03",
    excerpt: "From Table Mountain at dawn and Bo-Kaap's painted houses to African penguins at Boulders Beach, the UNESCO-listed Robben Island, and live jazz every night in De Waterkant: an honest four-day account of twenty encounters that explain why Cape Town is one of the most dramatically beautiful cities on earth.",
    category: "Tourism",
    readTime: "5 min",
    type: "AI+HI",
  },
  {
    id: 7,
    title: "Rio de Janeiro: Essential Encounters in the Cidade Maravilhosa",
    date: "2026-05-27",
    excerpt: "From the hike through Tijuca rainforest to Christ the Redeemer at dawn, Arpoador's applauding crowds at sunset, live samba in Lapa until 4 AM, and Michelin-starred counters in Botafogo: an honest account of twenty encounters that explain why Rio de Janeiro is one of the most dramatically beautiful cities on earth.",
    category: "Tourism",
    readTime: "5 min",
    type: "AI+HI",
  },
  {
    id: 6,
    title: "Tokyo: Twenty Essential Encounters in one of the World's Greatest Cities",
    date: "2026-05-27",
    excerpt: "From the organized bedlam of Shibuya Crossing at midnight to pre-dawn sushi at Tsukiji and jazz until 5 AM in Golden Gai — an honest account of twenty experiences that explain why Tokyo ruins you for every other city.",
    category: "Tourism",
    readTime: "5 min",
    type: "AI+HI",
  },
];

export default function TourismBlog() {
  const [filter, setFilter] = useState<string>("All");
  const categories = ["All", ...Array.from(new Set(posts.map((p) => p.category)))];
  const filteredPosts = filter === "All" ? posts : posts.filter((p) => p.category === filter);

  return (
    <main className="bg-gray-100 min-h-screen py-8 px-4 flex flex-col items-center relative md:py-12 md:px-8">

      {/* Hero */}
      <section
        className="relative w-full max-w-5xl rounded-2xl shadow-2xl overflow-hidden md:rounded-3xl"
        style={{
          backgroundImage: "url('/headerimages/1.jpeg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <div className="absolute inset-0 bg-gradient-to-b from-black/30 via-black/10 to-black/50"></div>

        <div className="relative px-6 py-12 md:px-16 md:py-16">
          <FadeIn>
            <div className="text-center text-white">
              <h1 className="text-3xl font-extrabold mb-2 drop-shadow-lg md:text-5xl">
                Tourism Blog
              </h1>
              <p className="text-base text-white/90 drop-shadow-sm md:text-lg md:text-xl">
                Travel stories, city guides, and things I&apos;ve discovered on the road.
              </p>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* Blog Posts */}
      <section className="relative w-full max-w-5xl mt-8 rounded-2xl shadow-lg px-6 py-12 md:mt-10 md:rounded-3xl md:px-16 md:py-16 bg-gray-200 transition-shadow duration-300 hover:shadow-xl">
        <FadeIn>
          <div className="text-center text-gray-700 mb-6">
            <p className="text-sm md:text-base leading-relaxed max-w-2xl mx-auto font-semibold">
              <span className="text-gray-900">Note:</span>
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-semibold bg-yellow-300 text-gray-900 ml-1 mr-1">AI + HI</span>
              &nbsp;posts are generated by one of the AI agents I&apos;ve built, then reviewed by Human Intelligence (myself or co-authors).
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-semibold bg-green-500 text-white ml-2 mr-1">HI</span>
              &nbsp;posts are written solely by myself or other co-authors.
            </p>
          </div>
        </FadeIn>
        <FadeIn>
          <div className="flex flex-wrap gap-2 justify-center mb-6 md:mb-8">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setFilter(cat)}
                aria-pressed={filter === cat}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                  filter === cat
                    ? "bg-gray-800 text-white shadow-md"
                    : "bg-white text-gray-700 hover:bg-gray-200"
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </FadeIn>

        <div className="grid gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
          {filteredPosts.map((post, i) => (
            <FadeIn key={post.id} delay={i * 100}>
              <article className="bg-white rounded-xl shadow-md hover:shadow-xl transition-shadow duration-300 overflow-hidden flex flex-col md:rounded-2xl">
                <div className="h-48 bg-gradient-to-br from-emerald-400 to-cyan-500 flex items-center justify-center relative">
                  <span className="text-white text-4xl font-bold opacity-30">{post.category}</span>
                  <span className={`absolute top-3 right-3 px-2 py-0.5 rounded-full text-[11px] font-bold leading-tight shadow-md ${
                    post.type === "AI+HI"
                      ? "bg-yellow-300 text-gray-900"
                      : "bg-green-500 text-white"
                  }`}>
                    {post.type}
                  </span>
                </div>
                <div className="p-6 flex flex-col flex-1">
                  <div className="flex items-center justify-between text-xs text-gray-500 mb-3">
                    <span>{new Date(post.date).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span>
                    <span>{post.readTime} read</span>
                  </div>
                  <h2 className="text-xl font-bold text-gray-900 mb-2">{post.title}</h2>
                  <p className="text-gray-600 text-sm leading-relaxed flex-1">{post.excerpt}</p>
                  <Link
                    href={`/tourism/blog/${post.id}`}
                    className="mt-4 inline-block text-gray-700 hover:text-gray-900 font-medium text-sm"
                  >
                    Read more &rarr;
                  </Link>
                </div>
              </article>
            </FadeIn>
          ))}
        </div>

        <div className="mt-8 text-center">
          <Link href="/blog" className="inline-block text-gray-600 hover:text-gray-900 font-medium text-sm underline">
            &larr; Back to AI &amp; Tech Blog
          </Link>
        </div>
      </section>

    </main>
  );
}
