"use client";

import { useState } from "react";
import Link from "next/link";
import FadeIn from "@/components/FadeIn";

interface BlogPost {
  id: number;
  title: string;
  date: string;
  excerpt: string;
  category: string;
  readTime: string;
  type: "AI+HI" | "HI";
}

const posts: BlogPost[] = [
  {
    id: 6,
    title: "This Week in AI: Anthropic Files for IPO, Nvidia Targets the AI PC, and Claude Rewrites Itself",
    date: "2026-06-08",
    excerpt: "Anthropic filed its IPO prospectus while simultaneously calling for an industry-wide AI slowdown - a combination that drew immediate skepticism. Nvidia entered the $200 billion PC chip market with RTX Spark. Microsoft shipped seven proprietary models to cut its OpenAI dependency, and OpenAI replaced its default ChatGPT model with GPT-5.5 Instant.",
    category: "AI",
    readTime: "5 min",
    type: "AI+HI",
  },
  {
    id: 5,
    title: "This Week in AI: Google Goes Agentic, OpenAI Proves a Theorem, and ChatGPT Gets Ads",
    date: "2026-05-26",
    excerpt: "An OpenAI reasoning model disproved an 80-year-old conjecture in discrete geometry. Google turned I/O into an agentic product launch with Gemini Spark and Gemini 3.5 Flash. OpenAI expanded its ad platform globally while Anthropic disclosed a model too dangerous to release — and targeted a $900 billion valuation.",
    category: "AI",
    readTime: "5 min",
    type: "AI+HI",
  },
  {
    id: 4,
    title: "Manus AI: The General Purpose Agent That Actually Works",
    date: "2026-05-19",
    excerpt: "Hands-on breakdown of Manus AI — what it is, how it works, and why it represents a real shift from chatbots to autonomous work agents.",
    category: "AI",
    readTime: "6 min",
    type: "AI+HI",
  },
  {
    id: 3,
    title: "From Prompts to Agents: A Practical Framework for Autonomous AI",
    date: "2026-05-09",
    excerpt: "A step-by-step guide to building production-ready AI agents — from simple prompt chaining to tool use, memory, and multi-agent orchestration with guardrails.",
    category: "AI",
    readTime: "5 min",
    type: "AI+HI",
  },
  {
    id: 1,
    title: "Generating AI Agents Using ChatGPT and Claude",
    date: "2026-05-04",
    excerpt: "How I combine ChatGPT and Claude to build autonomous agents that plan, reason, and execute multi-step tasks. A practical guide to dual-model orchestration.",
    category: "AI",
    readTime: "5 min",
    type: "AI+HI",
  },
  {
    id: 2,
    title: "Building a Daily AI News Agent with ChatGPT and Claude",
    date: "2026-05-04",
    excerpt: "A deep dive into my three-stage pipeline for automated AI news curation: scraping, filtering with GPT-4o-mini, and deep analysis with Claude Sonnet 4.",
    category: "AI",
    readTime: "5 min",
    type: "AI+HI",
  },
];

export default function Blog() {
  const [filter, setFilter] = useState<string>("All");
  const categories = ["All", ...Array.from(new Set(posts.map((p) => p.category)))];
  const filteredPosts = filter === "All" ? posts : posts.filter((p) => p.category === filter);

  return (
    <main className="bg-gray-100 min-h-screen py-8 px-4 flex flex-col items-center relative md:py-12 md:px-8">

      {/* Hero */}
      <section
        className="relative w-full max-w-5xl rounded-2xl shadow-2xl overflow-hidden md:rounded-3xl"
        style={{
          backgroundImage: "url('/headerimages/1.jpeg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <div className="absolute inset-0 bg-gradient-to-b from-black/30 via-black/10 to-black/50"></div>

        <div className="relative px-6 py-12 md:px-16 md:py-16">
          <FadeIn>
            <div className="text-center text-white">
              <h1 className="text-3xl font-extrabold mb-2 drop-shadow-lg md:text-5xl">
                Blog
              </h1>
              <p className="text-base text-white/90 drop-shadow-sm md:text-lg md:text-xl">
                Thoughts, tutorials, and things I&apos;ve learned along the way.
              </p>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* Blog Posts */}
      <section className="relative w-full max-w-5xl mt-8 rounded-2xl shadow-lg px-6 py-12 md:mt-10 md:rounded-3xl md:px-16 md:py-16 bg-gray-200 transition-shadow duration-300 hover:shadow-xl">
        <FadeIn>
          <div className="text-center text-gray-700 mb-6">
            <p className="text-sm md:text-base leading-relaxed max-w-2xl mx-auto font-semibold">
              <span className="text-gray-900">Note:</span>
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-semibold bg-yellow-300 text-gray-900 ml-1 mr-1">AI + HI</span>
              &nbsp;posts are generated by one of the AI agents I&apos;ve built, then reviewed by Human Intelligence (myself or co-authors).
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-semibold bg-green-500 text-white ml-2 mr-1">HI</span>
              &nbsp;posts are written solely by myself or other co-authors.
            </p>
          </div>
        </FadeIn>
        <FadeIn>
          <div className="flex flex-wrap gap-2 justify-center mb-6 md:mb-8">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setFilter(cat)}
                aria-pressed={filter === cat}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                  filter === cat
                    ? "bg-gray-800 text-white shadow-md"
                    : "bg-white text-gray-700 hover:bg-gray-200"
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </FadeIn>

        <div className="grid gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
          {filteredPosts.map((post, i) => (
            <FadeIn key={post.id} delay={i * 100}>
              <article className="bg-white rounded-xl shadow-md hover:shadow-xl transition-shadow duration-300 overflow-hidden flex flex-col md:rounded-2xl">
                <div className="h-48 bg-gradient-to-br from-blue-400 to-purple-500 flex items-center justify-center relative">
                  <span className="text-white text-4xl font-bold opacity-30">{post.category}</span>
                  <span className={`absolute top-3 right-3 px-2 py-0.5 rounded-full text-[11px] font-bold leading-tight shadow-md ${
                    post.type === "AI+HI"
                      ? "bg-yellow-300 text-gray-900"
                      : "bg-green-500 text-white"
                  }`}>
                    {post.type}
                  </span>
                </div>
                <div className="p-6 flex flex-col flex-1">
                  <div className="flex items-center justify-between text-xs text-gray-500 mb-3">
                    <span>{new Date(post.date).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span>
                    <span>{post.readTime} read</span>
                  </div>
                  <h2 className="text-xl font-bold text-gray-900 mb-2">{post.title}</h2>
                  <p className="text-gray-600 text-sm leading-relaxed flex-1">{post.excerpt}</p>
                  <Link
                    href={`/blog/${post.id}`}
                    className="mt-4 inline-block text-gray-700 hover:text-gray-900 font-medium text-sm"
                  >
                    Read more &rarr;
                  </Link>
                </div>
              </article>
            </FadeIn>
          ))}
        </div>
      </section>

      {/* Tourism link */}
      <section className="relative w-full max-w-5xl mt-8 rounded-2xl shadow-lg px-6 py-10 md:mt-10 md:rounded-3xl md:px-16 md:py-12 bg-gray-200 text-center">
        <p className="text-gray-700 text-sm md:text-base">
          ✈️ Also check out my travel guides &rarr;
          <Link href="/tourism/blog" className="text-gray-900 font-semibold hover:underline ml-1">
            Tourism Blog
          </Link>
        </p>
      </section>

    </main>
  );
}
